# Generated by Django 6.0.4 on 2026-04-19 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=25)),
                ('weight_kg', models.FloatField(default=70)),
                ('height_cm', models.FloatField(default=170)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('activity_days', models.IntegerField(default=3)),
                ('goal', models.CharField(choices=[('bulk', 'Bulk'), ('cut', 'Cut'), ('maintain', 'Maintain')], default='maintain', max_length=10)),
                ('diet_pref', models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Veg'), ('vegan', 'Vegan')], default='veg', max_length=10)),
                ('supplements', models.BooleanField(default=False)),
                ('location', models.CharField(choices=[('gym', 'Gym'), ('home', 'Home')], default='gym', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
